### ISSUE TITLE
报错了，提示 No module named items

### ISSUE THREAD

**Issue by LXMin** [BlackKnight7/spider#1]
![image](https://user-images.githubusercontent.com/20547898/30481484-8ba6d4b0-9a51-11e7-9832-4aca043d6fb4.png)
这一句话怎么会错呢，纳闷中。

**Comment by BlackKnight7** [comment]
的确是奇怪，你可以尝试改一改饮用items的路径，我一直用的linux，不确定是不是系统不同引起的。如果还有问题可以再联系我。
